In [ ]:
import random , csv
from pprint import pprint
import pandas as pd

class BMI(): 
    def __init__(self,name:str,height:int,weight:int): 
        self.name = name
        self.height = height
        self.weight = weight

    def get_bmi(self)->float: #取得bmi
        return round(self.weight / (self.height/100) ** 2,ndigits=2)
    
    def get_status(self)->str:  #取得status
        bmi = self.get_bmi()
        if bmi >=35:
            status = "重度肥胖"
        elif bmi >= 30:
            status = "中度肥胖"
        elif bmi >= 27:
            status = "輕度肥胖"
        elif bmi >= 24:
            status = "過重"
        elif bmi >= 18.5:
            status = "正常範圍"
        else:
            status = "體重過輕"
        return status

def get_name(nums:int=2)->list[str]: #抓取name.txt裡面的名字
    with open('names.txt',mode='r',encoding='utf-8') as file:
            names_str = file.read()
    names = names_str.split()
    names = random.choices(names,k=nums)
    return  names
     
def generate_bmi(names:list[str])->list[BMI]: 
    students:list[BMI] = []
    for name in names:
        height = random.randint(140,190)
        weight = random.randint(50,110)
        student_STATUS = BMI(name, height, weight)
        students.append(student_STATUS) #list實體化 
    return students

if __name__ == '__main__':
    nums = int(input('請輸入人數:'))
    names:list[str] = get_name(nums=nums)
    students:list[BMI] = generate_bmi(names=names)
    file_dict:list[dict] = []
    for student in students:
        #將資料轉換成字典
        student_dict = {
        "姓名": student.name,
        "身高": student.height,
        "體重": student.weight,
        "BMI": student.get_bmi(),
        "狀態": student.get_status()
        }
        file_dict.append(student_dict)  #寫入list[dict]
    
pprint(file_dict)#測試
df = pd.DataFrame(file_dict, 
                       columns=['姓名', '身高', '體重', 'BMI', '狀態'], #依據欄位名稱重新排序
                       index= range(1,nums+1)) #設定索引從1~nums(包含nums)
df.index.name = '學號'
df

[{'BMI': 37.06, '姓名': '陳怡珊', '狀態': '重度肥胖', '身高': 146, '體重': 79},
 {'BMI': 23.42, '姓名': '聶心怡', '狀態': '正常範圍', '身高': 156, '體重': 57},
 {'BMI': 37.65, '姓名': '唐雪豪', '狀態': '重度肥胖', '身高': 167, '體重': 105},
 {'BMI': 31.62, '姓名': '王雅琴', '狀態': '中度肥胖', '身高': 163, '體重': 84},
 {'BMI': 29.86, '姓名': '陳建豪', '狀態': '輕度肥胖', '身高': 183, '體重': 100},
 {'BMI': 22.64, '姓名': '黃柏宇', '狀態': '正常範圍', '身高': 153, '體重': 53},
 {'BMI': 36.2, '姓名': '劉昀天', '狀態': '重度肥胖', '身高': 162, '體重': 95},
 {'BMI': 32.45, '姓名': '陳嘉淑', '狀態': '中度肥胖', '身高': 158, '體重': 81},
 {'BMI': 22.1, '姓名': '周怡啟', '狀態': '正常範圍', '身高': 162, '體重': 58},
 {'BMI': 46.12, '姓名': '林珈發', '狀態': '重度肥胖', '身高': 142, '體重': 93}]

     姓名   身高   體重    BMI
學號
1   陳怡珊  146   79  37.06
2   聶心怡  156   57  23.42
3   唐雪豪  167  105  37.65
4   王雅琴  163   84  31.62
5   陳建豪  183  100  29.86
6   黃柏宇  153   53  22.64
7   劉昀天  162   95  36.20
8   陳嘉淑  158   81  32.45
9   周怡啟  162   58  22.10
10  林珈發  142   93  46.12

In [8]:
sdata = {'台北':[35000,60000,74000], '桃園':[71000,90000,120000], '台中':[16000,71000,90000], '高雄':[5000,34008,65000]}
pprint(sdata)

{'台中': [16000, 71000, 90000],
 '台北': [35000, 60000, 74000],
 '桃園': [71000, 90000, 120000],
 '高雄': [5000, 34008, 65000]}

In [9]:
df2 = pd.DataFrame(sdata)
df2

      台北      桃園     台中     高雄
0  35000   71000  16000   5000
1  60000   90000  71000  34008
2  74000  120000  90000  65000